<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\1.6\Assemblies\</OutputPath>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>YayosCombatAutoReloadFix</AssemblyName>
    <RootNamespace>YayosCombatAutoReloadFix</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.4.2">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <Reference Include="yayoCombat">
      <HintPath>References\yayoCombat.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="YayosCombatAddon">
      <HintPath>References\YayosCombatAddon.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
